import re
from functools import lru_cache

import dns.resolver
import httpx
import phonenumbers

from .models import FieldCheck

EMPTY_VALUES = {"", "n/a", "na", "nan", "none", "null", "-"}

EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")

DISPOSABLE_DOMAINS = {
    "mailinator.com",
    "tempmail.com",
    "10minutemail.com",
    "guerrillamail.com",
}

PARKED_MARKERS = [
    "domain is for sale",
    "buy this domain",
    "this domain may be for sale",
    "godaddy.com/domains",
    "domain parking",
    "this webpage was generated by the domain owner",
    "future home of something quite cool",
]

_resolver = dns.resolver.Resolver()
_resolver.timeout = 3
_resolver.lifetime = 3


def _is_empty(value: str) -> bool:
    return value.strip().lower() in EMPTY_VALUES


@lru_cache(maxsize=512)
def _has_mx_record(domain: str) -> bool:
    try:
        answers = _resolver.resolve(domain, "MX")
        return len(answers) > 0
    except Exception:
        try:
            # Some domains accept mail via an A record with no MX (rare but valid).
            _resolver.resolve(domain, "A")
            return True
        except Exception:
            return False


def validate_email(email: str) -> FieldCheck:
    if _is_empty(email):
        return FieldCheck(status="invalid", reason="Email is empty or N/A")

    email = email.strip()
    if not EMAIL_RE.match(email):
        return FieldCheck(status="invalid", reason="Email fails syntax check")

    domain = email.rsplit("@", 1)[-1].lower()
    if domain in DISPOSABLE_DOMAINS:
        return FieldCheck(status="invalid", reason="Disposable email domain")

    if not _has_mx_record(domain):
        return FieldCheck(status="invalid", reason=f"Domain '{domain}' has no MX/A record (mail cannot be delivered)")

    return FieldCheck(status="valid")


def validate_phone(phone: str, country_hint: str = "US") -> FieldCheck:
    if _is_empty(phone):
        return FieldCheck(status="invalid", reason="Phone is empty or N/A")

    try:
        parsed = phonenumbers.parse(phone.strip(), country_hint)
    except phonenumbers.NumberParseException as exc:
        return FieldCheck(status="invalid", reason=f"Phone could not be parsed ({exc.error_type.name})")

    if not phonenumbers.is_valid_number(parsed):
        return FieldCheck(status="invalid", reason="Phone number is invalid (bad length or country code)")

    return FieldCheck(status="valid")


def _looks_parked(body: str) -> bool:
    lowered = body.lower()
    return any(marker in lowered for marker in PARKED_MARKERS)


def validate_website(website: str) -> FieldCheck:
    if _is_empty(website):
        return FieldCheck(status="invalid", reason="Website is empty or N/A")

    url = website.strip()
    if not url.startswith(("http://", "https://")):
        url = f"https://{url}"

    try:
        with httpx.Client(follow_redirects=True, timeout=8.0) as client:
            response = client.get(url, headers={"User-Agent": "VerifiedCreditsBot/1.0"})
    except httpx.TimeoutException:
        return FieldCheck(status="invalid", reason="Website timed out")
    except httpx.ConnectError:
        return FieldCheck(status="invalid", reason="Website domain does not resolve / connection refused")
    except httpx.HTTPError as exc:
        return FieldCheck(status="invalid", reason=f"Website request failed ({type(exc).__name__})")

    if response.status_code >= 400:
        return FieldCheck(status="invalid", reason=f"Website returned HTTP {response.status_code}")

    if _looks_parked(response.text[:5000]):
        return FieldCheck(status="invalid", reason="Website looks like a parked/for-sale domain page")

    return FieldCheck(status="valid")
